config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :reservations
  resources :eateries
  devise_for :users
  resources :users do
    collection do
      post 'test'
    end
  end

  #put "test" => "users#test"

  root "eateries#index"



  get "about" => "pages#about"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
validates :party_size, :date, :time,
presence: { :message => "cannot be blank"}

belongs_to :eatery
belongs_to :user

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    #@reservations = Reservation.all
    @reservations = current_user.reservations #.order("created_at DESC")
    #@eateries = Eatery.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new

  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    #@reservation = current_user.reservations.build(eatery_params)

    #debugger
    @reservation.user_id = current_user.id


    if @reservation.save
      #debugger
      redirect_to @reservation, notice: 'Reservation was successfully created.'
    else
      #debugger
      render :new
    end

  end


  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
      if @reservation.update(reservation_params)
        redirect_to @reservation, notice: 'Reservation was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
      redirect_to reservations_url, notice: 'Reservation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:name,:email, :party_size, :date, :time, :comment, :eatery_id, :user_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for reservation, html: { multipart: true } do |f| %>

  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this@eatery from being saved:</h2>

        <ul>
          <% reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :party_size %>
        <%= f.number_field :party_size, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :date %>
        <%= f.date_select :date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :time %>
        <%= f.time_select :time, ampm:true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :comment %>
        <%= f.text_field :comment, class: "form-control" %>
      </div>

      <%= f.hidden_field :eatery_id, :value => eatery_id %>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>


<%= render partial: 'form', locals: {reservation: @reservation, eatery_id: @reservation.eatery_id}  %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
            <td> Eatery: <%= reservation.eatery_id %> </td>
            <td> Name: <%= reservation.name %> </td>
            <td> Party size: <%= reservation.party_size %> </td>
            <td> Date: <%= reservation.date %> </td>
            <td> Time: <%= reservation.time %> </td>
            <td><%= link_to 'Show', reservation_path(reservation) %></td>
          <% if reservation.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
            <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reservation.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reservation.time %>
</p>

<p>
  <strong>Party Size:</strong>
  <%= @reservation.party_size %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reservation.comment %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>