config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :reservations
  resources :eateries
  devise_for :users
  resources :users do
    collection do
      post 'test'
    end
  end

  #put "test" => "users#test"

  root "eateries#index"



  get "about" => "pages#about"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/eatery.rb
class Eatery < ApplicationRecord

  belongs_to :user
  has_and_belongs_to_many :categories
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true
  validates :image, presence: true
  validates :address, presence: true
  validates :description, presence: true

end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController
  before_action :set_eatery, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :allowed_to_create_eatery, only: [:edit, :new, :create]
  helper_method :owner?
  helper_method :patron?
  # GET /eateries
  # GET /eateries.json
  def index
    @eateries = Eatery.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    #@user = User.owner?

  end

  # GET /eateries/1
  # GET /eateries/1.json
  def show
    #debugger
    @reservation = Reservation.new
    #debugger
  end

  # GET /eateries/new
  def new
    @eatery = current_user.eateries.build

  end

  # GET /eateries/1/edit
  def edit
  end

  # POST /eateries
  # POST /eateries.json
  def create
    @eatery = current_user.eateries.build(eatery_params)

    if @eatery.save
      redirect_to @eatery, notice: 'Eatery was successfully created.'
    else
      render :new
    end

    #debugger
  end


  # PATCH/PUT /eateries/1
  # PATCH/PUT /eateries/1.json
  def update
      if @eatery.update(eatery_params)
        redirect_to @eatery, notice: 'Eatery was successfully updated.'
      else
        render :edit
      end

  end




  # DELETE /eateries/1
  # DELETE /eateries/1.json
  def destroy
    @eatery.destroy
    redirect_to eateries_url, notice: 'Eatery was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eatery
      @eatery = Eatery.find(params[:id])
    end

    def correct_user
      @eatery = current_user.eateries.find_by(id: params[:id])
      redirect_to eateries_path, notice: "Not authorized to edit this User" if @eatery.nil?
    end

    def allowed_to_create_eatery
      redirect_to eateries_path, notice: "Not authorized to create or edit an Eatery" if current_user.patron?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def eatery_params
      params.require(:eatery).permit(:name, :image, :address, :description, {category_ids:[]})
    end
end

app/helpers/eateries_helper.rb
module EateriesHelper

  def owner?
    debugger
    if current_user.try(:role) === "owner"
      #debugger
      true
    else
      false
    end

  end
end

app/views/eateries/_form.html.erb
<%= form_for @eatery, html: { multipart: true } do |f| %>
  <% if@eatery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eatery.errors.count, "error") %> prohibited this@eatery from being saved:</h2>

      <ul>
      <%@eatery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :categories %>
    <%=f.collection_check_boxes(:category_ids,Category.all,:id,:name)%>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/eateries/edit.html.erb
<h1>Editing Eatery</h1>

<%= render 'form', eatery: @eatery %>


<%= link_to 'Show', @eatery %> |
<%= link_to 'Back', eateries_path %>

app/views/eateries/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="eateries" class="transitions-enabled">
<% @eateries.each do |eatery| %>
  <div class="box" panel panel-default">

      <%= link_to image_tag(eatery.image.url(:medium)), eatery_path(eatery) %>
    <div class="panel-body">
      <p><strong><%= eatery.name %></strong></p>
      <%= eatery.user.name if eatery.user %><br/>
      <%= eatery.address %><br/>
      <%= eatery.description %><br/>
      <%= eatery.categories.collect{|o| o.name}.join(",") %>
      <%= eatery.categories.size %>
      <p><strong>User Role:</strong>
        <%= eatery.user.role%><br/>
      <% if eatery.user.role == "owner" && current_user && eatery.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_eatery_path(eatery) %>
            <%= link_to 'Destroy', eatery, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
      <% end %>
    </div>
  </div>
 <% end %>
</div>

<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/eateries/new.html.erb
<h1>New Eatery</h1>

<%= render 'form', eatery: @eatery %>

<%= link_to 'Back', eateries_path %>

app/views/eateries/show.html.erb
<%= link_to 'Back', eateries_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-6">
   <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @eatery.image.url(:medium) %>
      </div>
        <p><strong>Name:</strong>
          <%= @eatery.name if @eatery.user %>
        </p>
        <p><strong>Address:</strong>
          <%= @eatery.address %>
        </p>
        <p><%= @eatery.description %></p>
        <p><%= @eatery.categories.collect{|o| o.name}.join(",") %></p>


        <% if current_user && @eatery.user == current_user%>
          <%= render partial: 'reservations/form', locals: {reservation: @reservation, eatery_id: @eatery.id}  %>
          <%= link_to 'Edit', edit_eatery_path(@eatery) %> |
        <% end %>
    </div>
  </div>
</div>