config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :reservations
  resources :eateries
  devise_for :users
  resources :users do
    collection do
      post 'test'
    end
  end

  #put "test" => "users#test"

  root "eateries#index"



  get "about" => "pages#about"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ReservSter", root_path, class: "navbar-brand" %>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
            <% if current_user.owner? %>
              <li><%= link_to 'New Eatery', new_eatery_path %></li>
            <% end %>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |name,msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
      <%= yield %>
    </div>


  </body>
</html>